- hosts: ec2
  tasks:
    - name: create project folder
      file:
        path: /home/ubuntu/briw
        state: directory
      become: ubuntu
    - name: copy project to server
      synchronize:
        src: ~/academy/coffeProject/html/static_web/
        dest: /home/ubuntu/briw/
      become: ubuntu
    - name: build static web docker image
      docker_image:
        build:
          pull: no
          path: /home/ubuntu/briw
        name: briw_static
        source: build
        force_source: yes
      become: yes
    - name: remove container
      docker_container:
        name: briw_static
        state: absent
      become: yes
    - name: Run briw_static container
      docker_container:
        name: briw_static_container
        image: "briw_static:latest"
        ports:
          - "80:80"
      become: yes
